package com.hernaez.seven_eleven.model.dataaccesslayer.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hernaez.seven_eleven.model.dataaccesslayer.greendao.Order_Table;

import com.hernaez.seven_eleven.model.dataaccesslayer.greendao.Order_TableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig order_TableDaoConfig;

    private final Order_TableDao order_TableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        order_TableDaoConfig = daoConfigMap.get(Order_TableDao.class).clone();
        order_TableDaoConfig.initIdentityScope(type);

        order_TableDao = new Order_TableDao(order_TableDaoConfig, this);

        registerDao(Order_Table.class, order_TableDao);
    }
    
    public void clear() {
        order_TableDaoConfig.getIdentityScope().clear();
    }

    public Order_TableDao getOrder_TableDao() {
        return order_TableDao;
    }

}
