package com.hernaez.seven_eleven.model.dataaccesslayer.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ORDER__TABLE".
 */
public class Order_Table {

    private Long id;
    private String productName;
    private Integer productQty;
    private Integer productPrice;
    private Integer productSubtotal;
    private String productImgPath;

    public Order_Table() {
    }

    public Order_Table(Long id) {
        this.id = id;
    }

    public Order_Table(Long id, String productName, Integer productQty, Integer productPrice, Integer productSubtotal, String productImgPath) {
        this.id = id;
        this.productName = productName;
        this.productQty = productQty;
        this.productPrice = productPrice;
        this.productSubtotal = productSubtotal;
        this.productImgPath = productImgPath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Integer getProductQty() {
        return productQty;
    }

    public void setProductQty(Integer productQty) {
        this.productQty = productQty;
    }

    public Integer getProductPrice() {
        return productPrice;
    }

    public void setProductPrice(Integer productPrice) {
        this.productPrice = productPrice;
    }

    public Integer getProductSubtotal() {
        return productSubtotal;
    }

    public void setProductSubtotal(Integer productSubtotal) {
        this.productSubtotal = productSubtotal;
    }

    public String getProductImgPath() {
        return productImgPath;
    }

    public void setProductImgPath(String productImgPath) {
        this.productImgPath = productImgPath;
    }

}
