package com.hernaez.seven_eleven.model.dataaccesslayer.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ORDER_TABLE".
 */
public class OrderTable {

    private Long id;
    private String productName;
    private Integer productQty;
    private Double productPrice;
    private Double productSubtotal;
    private String productImgPath;

    public OrderTable() {
    }

    public OrderTable(Long id) {
        this.id = id;
    }

    public OrderTable(Long id, String productName, Integer productQty, Double productPrice, Double productSubtotal, String productImgPath) {
        this.id = id;
        this.productName = productName;
        this.productQty = productQty;
        this.productPrice = productPrice;
        this.productSubtotal = productSubtotal;
        this.productImgPath = productImgPath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Integer getProductQty() {
        return productQty;
    }

    public void setProductQty(Integer productQty) {
        this.productQty = productQty;
    }

    public Double getProductPrice() {
        return productPrice;
    }

    public void setProductPrice(Double productPrice) {
        this.productPrice = productPrice;
    }

    public Double getProductSubtotal() {
        return productSubtotal;
    }

    public void setProductSubtotal(Double productSubtotal) {
        this.productSubtotal = productSubtotal;
    }

    public String getProductImgPath() {
        return productImgPath;
    }

    public void setProductImgPath(String productImgPath) {
        this.productImgPath = productImgPath;
    }

}
